const express=require('express');
const Music=require('../models/music');
const router=express.Router();
const music_controller=require('../controllers/music_controller');
const passport=require('passport');

router.all('/upload_song_info/:user_id',passport.checkAuthentication,music_controller.upload_info);
router.all('/uploadPage',passport.checkAuthentication,music_controller.uploadPage);
router.all('/uploadSong/:name',passport.checkAuthentication,music_controller.uploadSong);
router.all('/upload_song/:id',passport.checkAuthentication,music_controller.upload_song);
router.all('/admin/upload',passport.checkAuthentication,music_controller.Adminupload);
router.all('/adminsongPage/:id',passport.checkAuthentication,music_controller.AdminSongUpload);
router.all('/uploadSongInfoAdmin',passport.checkAuthentication,music_controller.uploadSongInfoAdmin);
router.all('/uploadSongAdmin/:id',passport.checkAuthentication,music_controller.uploadSongAdmin);
router.all('/adminPlaylist/:name',passport.checkAuthentication,music_controller.playlistPage);
router.all('/addcategoryPage',passport.checkAuthentication,music_controller.addCategory);
router.all('/addcategoryimagePage/:id',passport.checkAuthentication,music_controller.addCategoryImage);
router.all('/createcategory',passport.checkAuthentication,music_controller.createCategory);
router.all('/uploadcategoryimage/:id',passport.checkAuthentication,music_controller.categoryImage);
router.all('/categories_list',passport.checkAuthentication,music_controller.categories_list);
module.exports=router;