const express=require('express');
const Music=require('../models/music');
const router=express.Router();
const music_controller=require('../controllers/music_controller');

router.all('/upload_song_info',music_controller.upload_info);
router.all('/uploadPage',music_controller.uploadPage);
router.all('/uploadSong/:name',music_controller.uploadSong);
router.all('/upload_song/:id',music_controller.upload_song);
router.all('/admin/upload',music_controller.Adminupload);
router.all('/adminsongPage/:id',music_controller.AdminSongUpload);
router.all('/uploadSongInfoAdmin',music_controller.uploadSongInfoAdmin);
router.all('/uploadSongAdmin/:id',music_controller.uploadSongAdmin);
router.all('/adminPlaylist/:name',music_controller.playlistPage);
router.all('/addcategoryPage',music_controller.addCategory);
router.all('/addcategoryimagePage/:id',music_controller.addCategoryImage);
router.all('/createcategory',music_controller.createCategory);
router.all('/uploadcategoryimage/:id',music_controller.categoryImage);
router.all('/categories_list',music_controller.categories_list);
module.exports=router;